
import java.sql.SQLException;
import javax.sql.rowset.CachedRowSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class Marksgrade extends javax.swing.JFrame {
    DatabaseManager dbm=new DatabaseManager();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Marksgrade.class.getName());

    /**
     * Creates new form Marksgrade
     */
    public Marksgrade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     void showData()
    {
         DatabaseManager dbManager = new DatabaseManager();
        String readData="SELECT admission_no, english, kiswahili , "
                +" maths , biology , chemistry , physics , geography, "
                + "history , religion ,agriculture ,computer,total ,average ,grade ,remarks FROM marks_grade WHERE admission_no=" + txtadmno.getText();
      System.out.print(readData);
        CachedRowSet dataset = dbManager.extractData(readData);
        if (dataset != null) 
        {
            try {
                
                while (dataset.next()) 
                {
                  txtadmno.setText(String.valueOf(dataset.getInt(1)));
                  
                   txtenglish.setText(String.valueOf(dataset.getInt(2)));
                   txtkiswahili.setText(String.valueOf(dataset.getInt(3)));
                   txtmaths.setText(String.valueOf(dataset.getInt(4)));
                   txtbio.setText(String.valueOf(dataset.getInt(5)));
                   txtchem.setText(String.valueOf(dataset.getInt(6)));
                   txtphysic.setText(String.valueOf(dataset.getInt(7)));
                   txtgeo.setText(String.valueOf(dataset.getInt(8)));
                   txthis.setText(String.valueOf(dataset.getInt(9)));
                   txtreli.setText(String.valueOf(dataset.getInt(10)));
                   txtagri.setText(String.valueOf(dataset.getInt(11)));
                   txtcomp.setText(String.valueOf(dataset.getInt(12)));
                   txttotal.setText(String.valueOf(dataset.getInt(13)));
                   txtaverage.setText(String.valueOf(dataset.getInt(14)));
                   txtgrade.setText(String.valueOf(dataset.getInt(15)));
                   txtremarks.setText(String.valueOf(dataset.getInt(16)));
                   
                 
                }
            }    
            catch (SQLException e)
            {
                System.err.println("Error reading person: " + e.getMessage());
            }
        }
  
    }
             
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtadmno = new javax.swing.JTextField();
        txtenglish = new javax.swing.JTextField();
        txtkiswahili = new javax.swing.JTextField();
        txtmaths = new javax.swing.JTextField();
        txtbio = new javax.swing.JTextField();
        txtchem = new javax.swing.JTextField();
        txtphysic = new javax.swing.JTextField();
        txtgeo = new javax.swing.JTextField();
        txthis = new javax.swing.JTextField();
        txtreli = new javax.swing.JTextField();
        txtagri = new javax.swing.JTextField();
        txtcomp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtgrade = new javax.swing.JTextField();
        txtremarks = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtaverage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ADMISSION NO:");

        jLabel2.setText("ENGLISH:");

        jLabel3.setText("KISWAHILI:");

        jLabel4.setText("MATHEMATICS:");

        jLabel5.setText("BIOLOGY:");

        jLabel6.setText("CHEMISTRY:");

        jLabel7.setText("PHYSICS:");

        jLabel8.setText("GEOGRAPHY:");

        jLabel9.setText("HISTORY:");

        jLabel10.setText("RELIGION:");

        jLabel11.setText("AGRICULTURE:");

        jLabel12.setText("COMPUTER:");

        txtenglish.addActionListener(this::txtenglishActionPerformed);

        txtmaths.addActionListener(this::txtmathsActionPerformed);

        txtphysic.addActionListener(this::txtphysicActionPerformed);

        txtagri.addActionListener(this::txtagriActionPerformed);

        jButton1.setText("SAVE");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("SEARCH");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("UPDATE");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Marks and grade");

        jLabel14.setText("TOTAL");

        jLabel15.setText("AVERAGE");

        jLabel16.setText("GRADE");

        jLabel17.setText("REMARKS");

        txttotal.addActionListener(this::txttotalActionPerformed);

        jButton4.setText("DELETE");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("CALCULATE");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)
                        .addGap(51, 51, 51)
                        .addComponent(jButton2)
                        .addGap(44, 44, 44)
                        .addComponent(jButton3)
                        .addGap(29, 29, 29)
                        .addComponent(jButton4)
                        .addGap(41, 41, 41)
                        .addComponent(jButton5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtphysic, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtchem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtbio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmaths, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtkiswahili, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtgeo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtenglish, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtadmno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(120, 120, 120)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel12))
                                            .addGap(31, 31, 31))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9))
                                            .addGap(62, 62, 62)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17))
                                        .addGap(52, 52, 52))))
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txthis)
                            .addComponent(txtreli)
                            .addComponent(txtcomp, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(txtagri)
                            .addComponent(txtremarks, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtaverage)
                            .addComponent(txttotal)
                            .addComponent(txtgrade)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtadmno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtenglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtreli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkiswahili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtagri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmaths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtbio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtchem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtaverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtphysic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtgrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtgeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtremarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtenglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenglishActionPerformed

    private void txtmathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmathsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmathsActionPerformed

    private void txtphysicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphysicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphysicActionPerformed

    private void txtagriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtagriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtagriActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (isValiddata())
        {
        int admissionno=Integer.parseInt(txtadmno.getText());
        String english=txtenglish.getText();
        String kiswahili=txtkiswahili.getText();
        String maths=txtmaths.getText();
        String biology =txtbio.getText();
        String chemistry=txtchem.getText();
        String physics=txtphysic.getText();
        String  geo=txtgeo.getText();
        String histo=txthis.getText();
        String religion=txtreli.getText();
        String agri=txtagri.getText();
        String comp=txtcomp.getText();
        String total=txttotal.getText();
        String average=txtaverage.getText();
        String grade=txtgrade.getText();
        String remarks=txtremarks.getText();

        String sql="INSERT INTO Marks_grade(admission_no,english"
        + ",kiswahili,maths,biology,chemistry,physics,geography,history,religion,"
        + "agriculture,computer,total,average,grade,remarks)"
        + "VALUES("+admissionno + ",\""  + english +
        "\", \"" + kiswahili + "\",\"" + maths + "\",\"" +
        biology + "\",\"" + chemistry + "\",\"" +physics +
        "\",\"" + geo + "\",\"" + histo +"\",\"" +religion +"\",\""
        + agri + "\",\"" + comp +"\",\"" + total +"\",\"" + average +"\",\"" + grade +"\",\"" +remarks+"\")";

        System.out.println(sql);
        dbm.createRecord(sql);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
private boolean isValiddata()
{
    if (txtadmno.getText().trim().isEmpty())
    {
        JOptionPane.showMessageDialog(null, "ENTER VALID USERNAME");
         return false;
    }
        return true;
    
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (isValiddata())
        {
        showData();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if (isValiddata())
        {
        DatabaseManager dbm=new DatabaseManager();
        String sql="update marks_grade SET english="+txtenglish.getText()+",kiswahili="+txtkiswahili.getText()+
                ",maths="+txtmaths.getText()+",biology="+txtbio.getText()+",chemistry="+txtchem.getText()+
                ",physics="+txtphysic.getText()+",geography="+txtgeo.getText()+",history="+txthis.getText()+
                ",religion="+txtreli.getText()+",agriculture="+txtagri.getText()+",computer="+txtcomp.getText()+
                ",total="+txttotal.getText()+",average="+txtaverage.getText()+",grade="+txtgrade.getText()+",remarks="+
                txtremarks.getText() + " where admission_no="+txtadmno.getText();
        System.out.print(sql);
        dbm.updateRecord(sql);
        }
        //JOptionPane.showMessageDialog(this,"Record updated successfully");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int english=Integer.parseInt(txtenglish.getText());
        int kiswahili=Integer.parseInt(txtkiswahili.getText());
        int maths=Integer.parseInt(txtmaths.getText());
        int biology=Integer.parseInt(txtbio.getText());
        int chemistry=Integer.parseInt(txtchem.getText());
        int physics=Integer.parseInt(txtphysic.getText());
        int geo=Integer.parseInt(txtgeo.getText());
        int histo=Integer.parseInt(txthis.getText());
        int religion=Integer.parseInt(txtreli.getText());
        int agri=Integer.parseInt(txtagri.getText());
        int comp=Integer.parseInt(txtcomp.getText());
        //Calculate total
        int total=english+kiswahili+maths+biology+chemistry+physics+geo+histo+religion+agri+comp;
          //Calculate average
          double average=total/11.0;
          //Display total and average
          txttotal.setText(String.valueOf(total));
          txtaverage.setText(String.valueOf((int)average));
          //Grade and remarks
          if(average>=80){txtgrade.setText("A");
          txtremarks.setText("Excellent");
          }else if(average>=70){txtgrade.setText("B");
          txtremarks.setText("Very good");
          }else if(average>=60){txtgrade.setText("C");
          txtremarks.setText("Good");
          }else if(average>=50){txtgrade.setText("D");
          txtremarks.setText("Pass");
          }else{txtgrade.setText("E");
          txtremarks.setText("Fail");
          }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       int deladmission_no=2;
        String sqlDel="DELETE FROM students WHERE admission_no=" + deladmission_no;
        dbm.deleteRecord(sqlDel);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Marksgrade().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtadmno;
    private javax.swing.JTextField txtagri;
    private javax.swing.JTextField txtaverage;
    private javax.swing.JTextField txtbio;
    private javax.swing.JTextField txtchem;
    private javax.swing.JTextField txtcomp;
    private javax.swing.JTextField txtenglish;
    private javax.swing.JTextField txtgeo;
    private javax.swing.JTextField txtgrade;
    private javax.swing.JTextField txthis;
    private javax.swing.JTextField txtkiswahili;
    private javax.swing.JTextField txtmaths;
    private javax.swing.JTextField txtphysic;
    private javax.swing.JTextField txtreli;
    private javax.swing.JTextField txtremarks;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
