/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author ADMIN
 */
import javax.sql.rowset.CachedRowSet;
import java.sql.SQLException;







public class students extends javax.swing.JFrame {
    DatabaseManager dbm=new DatabaseManager();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(students.class.getName());

    /**
     * Creates new form students
     */
    public students() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void showData()
    {
      
        DatabaseManager dbManager = new DatabaseManager();
        String readData="SELECT admission_no, full_name, gender, guardian_name, "
                + "father__name, mother_name, form, phone_no, address, "
                + "date_of_birth FROM students WHERE admission_no=" + txtAdmNo.getText();
        CachedRowSet dataset = dbManager.extractData(readData);
        if (dataset != null) 
        {
            try {
                
                while (dataset.next()) 
                {
                   txtAdmNo.setText(String.valueOf(dataset.getInt(1)));
                   txtName.setText(dataset.getString(2));
                   txtdateofbirth.setText(dataset.getString(10));
                   txtguardname.setText(dataset.getString(4));
                   txtfather.setText(dataset.getString(5));
                   txtmother.setText(dataset.getString(6));
                   txtphoneno.setText(dataset.getString(8));
                   txtaddress.setText(dataset.getString(9));
                   cmbform.getSelectedItem().toString();
                 
                }
                
            } 
            catch (SQLException e)
            {
                System.err.println("Error reading person: " + e.getMessage());
            }
        }
  
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        databaseManager1 = new DatabaseManager();
        jPanel1 = new javax.swing.JPanel();
        admission_no = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        date_of_birth = new javax.swing.JTextField();
        guardian = new javax.swing.JTextField();
        father = new javax.swing.JTextField();
        mother = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        txtAdmNo = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jrmale = new javax.swing.JRadioButton();
        jrfemale = new javax.swing.JRadioButton();
        txtdateofbirth = new javax.swing.JTextField();
        txtguardname = new javax.swing.JTextField();
        txtfather = new javax.swing.JTextField();
        txtmother = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbform = new javax.swing.JComboBox<>();
        form = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        phone = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        txtphoneno = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jTextField1.setText("STUDENT REGISTRATION FORM");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 40), new java.awt.Color(51, 51, 255))); // NOI18N

        admission_no.setText("ADMISSION NO");
        admission_no.addActionListener(this::admission_noActionPerformed);

        name.setText("FULL NAME");

        gender.setText("GENDER");

        date_of_birth.setText("DATE OF BIRTH");
        date_of_birth.addActionListener(this::date_of_birthActionPerformed);

        guardian.setText("GUARDIAN NAME");
        guardian.addActionListener(this::guardianActionPerformed);

        father.setText("FATHER'S NAME");
        father.addActionListener(this::fatherActionPerformed);

        mother.setText("MOTHER'S NAME");
        mother.addActionListener(this::motherActionPerformed);

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTextField10.setText("STUDENT REGISTRATION FORM");
        jTextField10.addActionListener(this::jTextField10ActionPerformed);

        txtAdmNo.addActionListener(this::txtAdmNoActionPerformed);

        txtName.addActionListener(this::txtNameActionPerformed);

        jrmale.setText("MALE");
        jrmale.addActionListener(this::jrmaleActionPerformed);

        jrfemale.setText("FEMALE");

        jButton1.setText("SAVE");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("DELETE");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        cmbform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Form 1", "Form 2", "Form 3", "Form 4" }));
        cmbform.addActionListener(this::cmbformActionPerformed);

        form.setText("FORM");

        jButton3.setText("UPDATE");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        phone.setText("PHONE NO ");

        address.setText("ADDRESS");
        address.addActionListener(this::addressActionPerformed);

        txtphoneno.addActionListener(this::txtphonenoActionPerformed);

        txtaddress.addActionListener(this::txtaddressActionPerformed);

        jButton4.setText("SEARCH");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(201, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mother)
                            .addComponent(father)
                            .addComponent(guardian)
                            .addComponent(admission_no)
                            .addComponent(name)
                            .addComponent(gender)
                            .addComponent(date_of_birth)
                            .addComponent(jButton1)
                            .addComponent(form)
                            .addComponent(phone)
                            .addComponent(address))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAdmNo)
                                            .addComponent(txtName)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jrmale)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                                .addComponent(jrfemale))
                                            .addComponent(txtdateofbirth)
                                            .addComponent(txtguardname)
                                            .addComponent(txtfather)
                                            .addComponent(txtmother)
                                            .addComponent(txtphoneno)
                                            .addComponent(txtaddress)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(114, 114, 114))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admission_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdmNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrmale))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(date_of_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtguardname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(father, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jrfemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void admission_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admission_noActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_admission_noActionPerformed

    private void guardianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardianActionPerformed
        // TODO add your handling code here:
        String txtgname=txtguardname.getText();
    }//GEN-LAST:event_guardianActionPerformed

    private void fatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherActionPerformed
        // TODO add your handling code here:
        String father=txtfather.getText();
    }//GEN-LAST:event_fatherActionPerformed

    private void date_of_birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_of_birthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_of_birthActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    int deladmission_no=2;
    String sqlDel="DELETE FROM students WHERE admission_no=" + deladmission_no;
    dbm.deleteRecord(sqlDel);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbformActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int admiss_no=Integer.parseInt(txtAdmNo.getText());
        String full_name=txtName.getText();
        String Gender="Female";
        String guardian_name=txtguardname.getText();
        String father_name=txtfather.getText();
        String mother_name=txtmother.getText();
        String Cform = String.valueOf(cmbform.getSelectedItem());
        String phone_no=txtphoneno.getText();
        String caddress=txtaddress.getText();
        String cdate_of_birth=txtdateofbirth.getText();
        
     
         String sql="INSERT INTO STUDENTS(admission_no, Full_Name,Gender,"
                 + "Guardian_Name,Father__Name,Mother_Name,Form,date_of_birth,Phone_no,Address)"
                 + "VALUES("+admiss_no + ",\"" + full_name + "\",\"" + Gender + 
                 "\", \"" + guardian_name + "\",\"" + father_name + "\",\"" +
                 mother_name + "\",\"" + Cform + "\",\"" +  cdate_of_birth + 
                 "\",\"" + phone_no + "\",\"" + caddress +"\")";
         System.out.println(sql);
         dbm.createRecord(sql);
         
         //String phone=txtphoneno.getText();
         //String address=txtaddress.getText();
         //String txtdob=txtdateofbirth.getText();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void txtAdmNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdmNoActionPerformed
        // TODO add your handling code here:
        String admno=txtAdmNo.getText();
    }//GEN-LAST:event_txtAdmNoActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
        String name=txtName.getText();
    }//GEN-LAST:event_txtNameActionPerformed

    private void jrmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrmaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrmaleActionPerformed

    private void motherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherActionPerformed
        // TODO add your handling code here:
        String mother=txtmother.getText();
    }//GEN-LAST:event_motherActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
        String address=txtaddress.getText();
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenoActionPerformed
        // TODO add your handling code here:
        String phone=txtphoneno.getText();
    }//GEN-LAST:event_txtphonenoActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int admiss_no=Integer.parseInt(txtAdmNo.getText());
        String full_name=txtName.getText();
        String Gender="Female";
        String guardian_name=txtguardname.getText();
        String father_name=txtfather.getText();
        String mother_name=txtmother.getText();
        String Cform = String.valueOf(cmbform.getSelectedItem());
        String phone_no=txtphoneno.getText();
        String caddress=txtaddress.getText();
        String cdate_of_birth=txtdateofbirth.getText();
       String sql="update students SET  full_name=\"" + full_name + "\", gender=\"" + Gender  + 
                 "\", guardian_name=\"" + guardian_name + "\",father__name=\"" + father_name + "\",mother_name=\"" +
                 mother_name + "\",form=\"" + Cform + "\",date_of_birth=\"" +  cdate_of_birth +
                 "\",phone_no=\"" + phone_no + "\",address=\"" + caddress +"\" WHERE admission_no=" + admiss_no;
       
        System.out.println(sql);
         dbm.updateRecord(sql);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        showData();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new students().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField admission_no;
    private javax.swing.JComboBox<String> cmbform;
    private DatabaseManager databaseManager1;
    private javax.swing.JTextField date_of_birth;
    private javax.swing.JTextField father;
    private javax.swing.JTextField form;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField guardian;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JRadioButton jrfemale;
    private javax.swing.JRadioButton jrmale;
    private javax.swing.JTextField mother;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField txtAdmNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdateofbirth;
    private javax.swing.JTextField txtfather;
    private javax.swing.JTextField txtguardname;
    private javax.swing.JTextField txtmother;
    private javax.swing.JTextField txtphoneno;
    // End of variables declaration//GEN-END:variables
}

