/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
import javax.sql.rowset.CachedRowSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

   
       
public class SubjectMarks extends javax.swing.JFrame {
    DatabaseManager dbm=new DatabaseManager();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SubjectMarks.class.getName());

    /**
     * Creates new form SubjectMarks
     */
    public SubjectMarks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void showData()
    {
         DatabaseManager dbManager = new DatabaseManager();
        String readData="SELECT admission_no, name, english, kiswahili , "
                +" maths biology , chemistry , physics , geography, "
                + "history , religion ,agriculture ,computer FROM form1 WHERE admission_no=" + txtadmiss.getText();
        CachedRowSet dataset = dbManager.extractData(readData);
        if (dataset != null) 
        {
            try {
                
                while (dataset.next()) 
                {
                   txtadmiss.setText(String.valueOf(dataset.getInt(13)));
                   name.setText(dataset.getString(1));
                   txtenglish.setText(String.valueOf(dataset.getInt(2)));
                   txtkis.setText(String.valueOf(dataset.getInt(3)));
                   txtmaths.setText(String.valueOf(dataset.getInt(4)));
                   txtbio.setText(String.valueOf(dataset.getInt(5)));
                   txtchem.setText(String.valueOf(dataset.getInt(6)));
                   txtphysic.setText(String.valueOf(dataset.getInt(7)));
                   txtgeo.setText(String.valueOf(dataset.getInt(8)));
                   txthisto.setText(String.valueOf(dataset.getInt(9)));
                   txtreli.setText(String.valueOf(dataset.getInt(10)));
                   txtagri.setText(String.valueOf(dataset.getInt(11)));
                   txtcomp.setText(String.valueOf(dataset.getInt(12)));
                 
                }
                
            } 
            catch (SQLException e)
            {
                System.err.println("Error reading person: " + e.getMessage());
            } 
               
    } 
    }
       
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        admissionno = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        english = new javax.swing.JLabel();
        kiswahili = new javax.swing.JLabel();
        maths = new javax.swing.JLabel();
        biology = new javax.swing.JLabel();
        chemistry = new javax.swing.JLabel();
        physics = new javax.swing.JLabel();
        geo = new javax.swing.JLabel();
        histo = new javax.swing.JLabel();
        religion = new javax.swing.JLabel();
        agri = new javax.swing.JLabel();
        comp = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        search = new javax.swing.JButton();
        txtadmiss = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtenglish = new javax.swing.JTextField();
        txtkis = new javax.swing.JTextField();
        txtmaths = new javax.swing.JTextField();
        txtbio = new javax.swing.JTextField();
        txtchem = new javax.swing.JTextField();
        txtgeo = new javax.swing.JTextField();
        txthisto = new javax.swing.JTextField();
        txtphysic = new javax.swing.JTextField();
        txtreli = new javax.swing.JTextField();
        txtagri = new javax.swing.JTextField();
        txtcomp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("        FORM 1");

        admissionno.setText("ADMISSION NO:");

        name.setText("STUDENT NAME:");

        english.setText("ENGLISH:");

        kiswahili.setText("KISWAHILI:");

        maths.setText("MATHEMATICS:");

        biology.setText("BIOLOGY:");

        chemistry.setText("CHEMISTRY:");

        physics.setText("PHYSICS:");

        geo.setText("GEOGRAPHY:");

        histo.setText("HISTORY:");

        religion.setText("RELIGION:");

        agri.setText("AGRICULTURE:");

        comp.setText("COMPUTER:");

        save.setText("SAVE");
        save.addActionListener(this::saveActionPerformed);

        delete.setText("DELETE");
        delete.addActionListener(this::deleteActionPerformed);

        search.setText("SEARCH");
        search.addActionListener(this::searchActionPerformed);

        txtadmiss.addActionListener(this::txtadmissActionPerformed);

        txtenglish.addActionListener(this::txtenglishActionPerformed);

        txtmaths.addActionListener(this::txtmathsActionPerformed);

        txtbio.addActionListener(this::txtbioActionPerformed);

        txtgeo.addActionListener(this::txtgeoActionPerformed);

        txthisto.addActionListener(this::txthistoActionPerformed);

        txtphysic.addActionListener(this::txtphysicActionPerformed);

        txtreli.addActionListener(this::txtreliActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(save)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kiswahili, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(maths)
                                        .addComponent(biology)))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtadmiss, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtenglish, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtkis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(101, 101, 101)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(geo)
                                                    .addComponent(physics)
                                                    .addComponent(histo)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtmaths, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(religion)
                                                .addGap(20, 20, 20))
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtbio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtchem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(98, 98, 98)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(comp)
                                                .addComponent(agri)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(search)
                                            .addGap(13, 13, 13)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(delete)
                                        .addGap(175, 175, 175)))))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txthisto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtgeo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtagri, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtreli, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcomp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtphysic, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(admissionno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chemistry)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admissionno)
                    .addComponent(txtadmiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(english)
                                            .addComponent(txtenglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtgeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(physics)
                                .addGap(24, 24, 24)
                                .addComponent(geo)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(histo)
                                .addComponent(txthisto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kiswahili))
                            .addComponent(txtkis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtphysic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(religion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtreli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agri)
                            .addComponent(txtagri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maths)
                            .addComponent(txtmaths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(biology)
                            .addComponent(txtbio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(chemistry))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtchem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comp)
                            .addComponent(txtcomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(delete)
                    .addComponent(search))
                .addGap(18, 56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
         if (isValiddata())
        {
         int admissionno=Integer.parseInt(txtadmiss.getText());
        String name=txtname.getText();
        String english=txtenglish.getText();
        String kiswahili=txtkis.getText();
        String maths=txtmaths.getText();
        String biology =txtbio.getText();
        String chemistry=txtchem.getText();
        String physics=txtgeo.getText();
        String  geo=txthisto.getText();
        String histo=txtphysic.getText();
        String religion=txtreli.getText();
        String agri=txtagri.getText();
        String comp=txtcomp.getText();
        
     
         String sql="INSERT INTO FORM1(admission_no, name,english"
                 + ",kiswahili,maths,biology,chemistry,physics,geography,history,religion,"
                 + "agriculture,computer)"
                 + "VALUES("+admissionno + ",\"" + name + "\",\"" + english + 
                 "\", \"" + kiswahili + "\",\"" + maths + "\",\"" +
                 biology + "\",\"" + chemistry + "\",\"" +physics + 
                 "\",\"" + geo + "\",\"" + histo +"\",\"" +religion +"\",\""
         + agri + "\",\"" + comp +"\")";
         
         System.out.println(sql);
         dbm.createRecord(sql);
        }
    }//GEN-LAST:event_saveActionPerformed
private boolean isValiddata()
{
    if (txtadmiss.getText().trim().isEmpty())
    {
        JOptionPane.showMessageDialog(null, "ENTER VALID USERNAME");
         return false;
    }
        return true;
}


    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code her
       if (isValiddata())
        {
   
         int deladmission_no=2;
    String sqlDel="DELETE FROM students WHERE admission_no=" + deladmission_no;
    dbm.deleteRecord(sqlDel);
        
        }  
    }//GEN-LAST:event_deleteActionPerformed

    private void txtreliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreliActionPerformed
        // TODO add your handling code here:
        String raligion=txtreli.getText();
    }//GEN-LAST:event_txtreliActionPerformed

    private void txtenglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenglishActionPerformed
        // TODO add your handling code here:
        String english=txtenglish.getText();
    }//GEN-LAST:event_txtenglishActionPerformed

    private void txtmathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmathsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmathsActionPerformed

    private void txtadmissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadmissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadmissActionPerformed

    private void txthistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthistoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthistoActionPerformed

    private void txtgeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgeoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgeoActionPerformed

    private void txtbioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbioActionPerformed

    private void txtphysicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphysicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphysicActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
         if (isValiddata())
        {
        showData();
        
    }//GEN-LAST:event_searchActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SubjectMarks().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admissionno;
    private javax.swing.JLabel agri;
    private javax.swing.JLabel biology;
    private javax.swing.JLabel chemistry;
    private javax.swing.JLabel comp;
    private javax.swing.JButton delete;
    private javax.swing.JLabel english;
    private javax.swing.JLabel geo;
    private javax.swing.JLabel histo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kiswahili;
    private javax.swing.JLabel maths;
    private javax.swing.JLabel name;
    private javax.swing.JLabel physics;
    private javax.swing.JLabel religion;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTextField txtadmiss;
    private javax.swing.JTextField txtagri;
    private javax.swing.JTextField txtbio;
    private javax.swing.JTextField txtchem;
    private javax.swing.JTextField txtcomp;
    private javax.swing.JTextField txtenglish;
    private javax.swing.JTextField txtgeo;
    private javax.swing.JTextField txthisto;
    private javax.swing.JTextField txtkis;
    private javax.swing.JTextField txtmaths;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphysic;
    private javax.swing.JTextField txtreli;
    // End of variables declaration//GEN-END:variables
}
